// Sample airport data (Indian airports)
// export const airportShortData = [
//     { id: 1, name: 'Indira Gandhi International Airport, Delhi' },
//     { id: 2, name: 'Chhatrapati Shivaji Maharaj International Airport, Mumbai' },
//     { id: 3, name: 'Kempegowda International Airport, Bengaluru' },
//     { id: 4, name: 'Rajiv Gandhi International Airport, Hyderabad' },
//     { id: 5, name: 'Netaji Subhas Chandra Bose International Airport, Kolkata' },
//     { id: 6, name: 'Cochin International Airport' },
//     { id: 7, name: 'Goa International Airport' },
//     { id: 8, name: 'Jaipur International Airport' },
//     { id: 9, name: 'Sardar Vallabhbhai Patel International Airport, Ahmedabad' },
//     { id: 10, name: 'Chennai International Airport' },
//     { id: 11, name: 'Pune Airport' },
//     { id: 12, name: 'Bagdogra Airport' },
//     { id: 13, name: 'Lal Bahadur Shastri Airport, Varanasi' },
//     { id: 14, name: 'Devi Ahilya Bai Holkar Airport, Indore' },
//     { id: 15, name: 'Bhubaneswar Airport' },
//     { id: 16, name: 'Sri Guru Ram Dass Jee International Airport, Amritsar' },
//     { id: 17, name: 'Lokpriya Gopinath Bordoloi International Airport, Guwahati' },
//     { id: 18, name: 'Birsa Munda Airport, Ranchi' },
//     { id: 19, name: 'Jodhpur Airport' },
//     { id: 20, name: 'Trivandrum International Airport' },
//     // Add more Indian airports here if needed
// ];
export const airportData = [
    { id: 1, name: ' Delhi' },
    { id: 2, name: 'Mumbai' },
    { id: 3, name: 'Bengaluru' },
    { id: 4, name: 'Hyderabad' },
    { id: 5, name: 'Kolkata' },
    { id: 6, name: 'Cochin ' },
    { id: 7, name: 'Goa ' },
    { id: 8, name: 'Jaipur' },
    { id: 9, name: ' Ahmedabad' },
    { id: 10, name: 'Chennai ' },
    { id: 11, name: 'Pune ' },
    { id: 12, name: 'Bagdogra' },
    { id: 13, name: 'Varanasi' },
    { id: 14, name: 'Indore' },
    { id: 15, name: 'Bhubaneswar ' },
    { id: 16, name: ' Amritsar' },
    { id: 17, name: ' Guwahati' },
    { id: 18, name: ' Ranchi' },
    { id: 19, name: 'Jodhpur ' },
    { id: 20, name: 'Trivandrum ' },
    // Add more Indian airports here if needed
];