// images.js
import trainImage from './images/train-4 (1).png';
import indian_flag from '../assets/images/flags/Indian_flag.png';
import charminar from  '../assets/images/charminar.png';
import benglore from '../assets/images/Bangalore.png';
import kolkota from '../assets/images/kolkata.png';
import mumbai from '../assets/images/mumbai.png';
import utterpradesh from '../assets/images/Uttrapradesh.png';
import kerla from '../assets/images/kerala.png'
import delhi from '../assets/images/delhi.png'
import chennai from '../assets/images/chennai.png';
import youngIndianCouple from '../assets/images/young-indian-couple-together-airport 1.png';
import team1 from '../assets/images/Testimonials/team-1.webp'
import team2 from '../assets/images/Testimonials/team-2.webp'
import team3 from '../assets/images/Testimonials/team-3.webp'
import team4 from '../assets/images/Testimonials/team-4.webp'
import team5 from '../assets/images/Testimonials/team-5.webp'
import indianTrain from '../assets/images/indian_train.png'
import login from '../assets/images/Traveling-pana.png'
import charminar2 from '../assets/images/charminar-2.png'
import ramoji from '../assets/images/ramoji.png'
import gloconda from '../assets/images/gloconda_fort.png'
import D from '../assets/images/D.png'
import UPI from '../assets/images/upi-icon.png'
import Indigo from '../assets/images/6E.png'
import AirIndia from '../assets/images/AI.png'
import Vistara from '../assets/images/UK.png'
import Hyderabad from '../assets/images/Hyderbad.png'
import indigo from '../assets/images/6E.png';
import Mumbai from '../assets/images/mumbai-1.png';
import Bangalore from '../assets/images/Bangalore-1.png';
import Delhi from '../assets/images/Delhi-1.png';
import Hotel01 from '../assets/images/Hotel-1.jpeg';
import Hotel02 from '../assets/images/Hotel-2.jpeg';
import Hotel03 from '../assets/images/Hotel-3.jpeg';
import Hotel04 from '../assets/images/Hotel-4.jpeg';
import Nexon from '../assets/images/nexon.png';
import Carnival from '../assets/images/carnival.png';
import Jazz from '../assets/images/HondaJazz.png';
import Ertiga from '../assets/images/Ertiga.png';
import Toyota from '../assets/images/toyota.png';
import Tiago from '../assets/images/tiago.png';
import ship1 from '../assets/images/ship-1.png';
import ship2 from '../assets/images/ship-2.png';
import ship3 from '../assets/images/ship-3.png';
import ship4 from '../assets/images/ship-4.png';
import ship5 from '../assets/images/ship-5.png';
import ship6 from '../assets/images/ship-6.png';
import bus1 from '../assets/images/bus-1.png';
import bus2 from '../assets/images/bus-2.png';
import bus3 from '../assets/images/bus-3.png';
import bus4 from '../assets/images/bus-4.png';
import bus5 from '../assets/images/bus-5.png';
import bus6 from '../assets/images/bus-6.png';
import bus7 from '../assets/images/bus7.png';
import bus8 from '../assets/images/bus8.png';
import bus9 from '../assets/images/bus9.png';
import bus10 from '../assets/images/bus10.png';
import bus11 from '../assets/images/bus11.png';
import bus12 from '../assets/images/Bus12.jpg';
import Logowhite from '../assets/images/logo-white.png';
import cab from '../assets/images/cab.png'
import bus from '../assets/images/bus.png'
import MedicalTourismImage from '../assets/images/MedicalTourismImage.jpg'
import DoctorImage from './images/DoctorImage.jpg'
import Playstoreicon from '../assets/images/google-play.png'
import Appstoreicon from '../assets/images/app_store.png'
import Homevilla from '../assets/images/villa.svg'
import selfdrive from '../assets/images/self-drive.svg';
import Insurance from '../assets/images/Insurance.svg';
import Packagesimage from '../assets/images/Packages.svg';
import PopupImage from '../assets/images/popup_image.jpg';
import offer from '../assets/images/offer_image.png';
import Healthissues1 from '../assets/images/Healthissues/Healthissue-1.png';
import Healthissues2 from '../assets/images/Healthissues/Healthissue-2.png';
import Healthissues3 from '../assets/images/Healthissues/Healthissue-3.png';
import Healthissues4 from '../assets/images/Healthissues/Healthissue-4.png';
import Healthissues5 from '../assets/images/Healthissues/Healthissue-5.png';
import Healthissues6 from '../assets/images/Healthissues/Healthissue-6.png';
import Irctc from '../assets/images/Whyseemytrip/Irctc.png'
import refund from '../assets/images/Whyseemytrip/Refund.png'
import upi from '../assets/images/Whyseemytrip/UPI.png'
import Trainoffer from '../assets/images/Whyseemytrip/Train_offer.png'
import auth from '../assets/img/auth.svg'

export {
  trainImage,indian_flag,charminar,benglore, kolkota, mumbai, utterpradesh, kerla, delhi,chennai,youngIndianCouple, team1, indianTrain,team2,team3,team4,team5,login,charminar2,ramoji,gloconda,D,UPI,Indigo,AirIndia,Vistara,Hyderabad,indigo,Mumbai,Bangalore,Delhi,Hotel01,Hotel02,Hotel03,Hotel04,Nexon,Carnival,Jazz,Ertiga,Toyota,Tiago,ship1,ship2,ship3,ship4,ship5,ship6,bus1,bus2,bus3,bus4,bus5,bus6,bus7,bus8,bus9,bus10,cab,bus,bus11,bus12,MedicalTourismImage,DoctorImage,Playstoreicon,Appstoreicon,Homevilla,selfdrive,Insurance,Packagesimage,PopupImage,offer,Healthissues1,Healthissues2,Healthissues3,Healthissues4,Healthissues5,Healthissues6,Irctc,auth,refund,upi,Trainoffer
};
